### ISSUE TITLE
npm install 问题

### ISSUE THREAD

**Issue by fatesinger** [Treri/vue-ios-alertview#1]
通过 npm 安装默认会少dist文件夹，你的入口文件在 dist 里。得手动 npm run build ，另外windows下不支持rm。sad

**Comment by ik0r** [comment]
好 我更新一下

**Comment by ik0r** [comment]
已经更新 v1.1.1

**Comment by fatesinger** [comment]
感人！是否会考虑移动端适配的问题

**Comment by ik0r** [comment]
这个目前应该就可以在移动端使用吧, 你用chrome的模拟手机去看demo应该是正常的

不要看dmeo页面本身, 那个我没有做适配, 你看弹出的弹窗的效果就行了

**Comment by fatesinger** [comment]
原来是使用 flexible rem 布局dpr的问题。
