### ISSUE TITLE
调用以后再uc页面打不开了

### ISSUE THREAD

**Issue by ulo-huangsz** [Treri/vue-ios-alertview#2]
调用以后再uc页面打不开了

**Comment by ik0r** [comment]
说详细点.
你这一句话, 怎么定位?

**Comment by ulo-huangsz** [comment]
安装之后，引入依赖，然后在一个移动端页面中调用this.$iosAlert('alert')后，代码运行后页面只能在微信端和iOS的操作系统打开，在支付宝等uc内核的浏览器打不开页面

**Comment by ik0r** [comment]
有没有报错信息? 能不能给个demo

**Comment by ulo-huangsz** [comment]
没有报错信息 
------------------ Original ------------------

**Comment by ik0r** [comment]
确实有问题, 找了个安卓的UC浏览器, 确实无法弹出. 我看一下吧

**Comment by ik0r** [comment]
published v1.1.2
请更新最新版吧

**Comment by ulo-huangsz** [comment]
1. C:\Users\Administrator\Desktop\bug\alipay1.0\demo\demo\my-project>npm install vue-ios-alertview
my-project@1.0.0 C:\Users\Administrator\Desktop\bug\alipay1.0\demo\demo\my-project-- vue-ios-alertview@1.1.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2. package.json  
 "types": "types/index.d.ts",
  "version": "1.1.1"
重新安装之后怎么还是1.1.1的版本

**Comment by ik0r** [comment]
https://www.npmjs.com/package/vue-ios-alertview

**Comment by ulo-huangsz** [comment]
大神请教你个问题，你一般封装vue控件的步骤是怎么的，比如封装一些loading，alert，你项目中遇到的一些需要自己封装的等等

**Comment by ik0r** [comment]
@ulo-huangsz 
其实按我的理解, loading, alert 这些的应该属于动态modal, 其它的在页面中展示组件就是属于正常的控件

像这些

- https://github.com/Treri/vue-sui-toast
- https://github.com/Treri/vue-sui-loading
- https://github.com/Treri/vue-ios-alertview
- https://github.com/Treri/vue-ios-actionsheet

这些都属于动态modal, 虽然 Vue 官方不鼓励动态插入, 但是我们还是可以做到. 这样的组件, 就是先把展示的东西做好, 然后再想怎么动态插入就行了.

其它一些那种业务中用到的展示或者交互组件, 就是正常的划分边界, 然后封装, 对外提供事件或者接口就行了.

不知道这些对你有没有什么帮助. 如果有说的不明白的还希望指出

**Comment by ulo-huangsz** [comment]
我想了解的就是你提到的最后一点“其它一些那种业务中用到的展示或者交互组件, 就是正常的划分边界, 然后封装, 对外提供事件或者接口就行了.”   对外提供事件或者接口，需要的地方直接调用 ，这个过程怎么实现，你有没有封装的demo之类的 
 
------------------ Original ------------------
From: "Treri Liu"; 
Date: 2017年6月20日(星期二) 下午4:24
To: "Treri/vue-ios-alertview"; 
Cc: "ulo-huangsz"; "Mention"; 
Subject: Re: [Treri/vue-ios-alertview] 调用以后再uc页面打不开了 (#2)

 

@ulo-huangsz
 其实按我的理解, loading, alert 这些的应该属于动态modal, 其它的在页面中展示组件就是属于正常的控件
 
像这些
  
https://github.com/Treri/vue-sui-toast
 
https://github.com/Treri/vue-sui-loading
 
https://github.com/Treri/vue-ios-alertview
 
https://github.com/Treri/vue-ios-actionsheet
  
这些都属于动态modal, 虽然 Vue 官方不鼓励动态插入, 但是我们还是可以做到. 这样的组件, 就是先把展示的东西做好, 然后再想怎么动态插入就行了.
 
其它一些那种业务中用到的展示或者交互组件, 就是正常的划分边界, 然后封装, 对外提供事件或者接口就行了.
 
不知道这些对你有没有什么帮助. 如果有说的不明白的还希望指出

**Comment by ik0r** [comment]
这种组件其实还可以再划分

有一些为通用型组件, 它们和具体的业务没有太多关系, 只是提供通用功能或者功能增强. 比如用vue封装的jquery插件select2, 还有input增强型组件. 这种组件的要求就比较高一些, 要求的复用性还有和业务无关性

还有一些是和业务有耦合的. 虽然有耦合, 但是也可以进行一定的封装. 这种组件要求就低一些, 可能一大块代码就可以封装成一个组件, 我认为这样的组件不太要求复用性, 封装的目的主要是来减少页面的复杂度, 帮助理解整体代码结构, 页面结构.

至于你说的这个过程怎么实现, 可能还是要看具体的场景吧.
